### ISSUE TITLE
Add documentation for template supported features & components

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#110]
## Why

The `Flutter Templates` includes some pre-setup features & components, which help the developer to initialize and start their project more efficiently and rapidly. We should mention all supported features & components, such as TokenAuthentication or permission_handler, to know better what's supported and what needs more effort to set up.

Also, not all existing features & components are always needed for all projects. Having a list of supported features & components lets the developer know to clean up some TODO parts of the template project. 💪 
 
## Who Benefits?

Developers

**Comment by sleepylee** [comment]
does that mean before a developer use our template they have to read through the whole Wiki to understand what they will need or not need from the pre-setup?
Documenting what we have done is fine it's a great addition, but I don't think this resolves the issue we mentioned in #109

**Comment by luongvo** [comment]
@sleepylee Since we completed this feature https://github.com/nimblehq/flutter-templates/issues/160 to move that lib out of the core template, your concern is now resolved. We can focus on the document update in this ticket 🚀

**Comment by sleepylee** [comment]
all good
