### ISSUE TITLE
[Generate project with Mason] Update necessary CI/CD workflows to use the new script

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter-templates#184]
## Why

After integrating the template with Mason, we have to replace it with the legacy Python scripts in all existing workflows.

This is what we need to cover in this task:
- Replace the Python script.
- Update necessary CI/CD workflows to use the new script:
  - [test.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/test.yml).
  - [android_deploy_staging.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_staging.yml)
  - [android_deploy_production_to_playstore.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_production_to_playstore.yml)
  - [android_deploy_production.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_production.yml)
 
## Who Benefits?

Developers

**Comment by luongvo** [comment]
@manh-t Most of steps here are covered by https://github.com/nimblehq/flutter-templates/issues/137, I'll modify this ticket to only 
- Replace the Python script.
- Update necessary CI/CD workflows to use the new script.

**Comment by luongvo** [comment]
@manh-t I moved these AC from #162 to this ticket. All good now.
- Replace the Python script.
- Update necessary CI/CD workflows to use the new script.
