### ISSUE TITLE
[Generate project with Mason] Add the generated code to `develop` branch after merging a pull request

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter-templates#185]
## Why

When implementing a feature or fixing a bug/ chore, there should be a generated project to demonstrate the template's work. So, we will do this step automatically by running a job in CICD after a pull request is merged to `develop`.
- To ensure the generated project works properly, the project should be buildable and runnable before pushing the generated code.
The CICD steps should be:
- Generate the project with Mason.
- Run code generator and unit test for the generated project.
- If there is no error, do push a commit with the generated project to `develop` branch under `generated/` directory. (we can remove the old generated project before pushing a new code to get rid of conflicting).
 
## Who Benefits?

Developers

**Comment by luongvo** [comment]
@manh-t I combined this ticket with #159, I'll close this ticket.
