### ISSUE TITLE
Generate and add "release notes" when distributing new builds on Firebase (staging and production)

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#198]
## Why

Currently, the template supports existing CD workflows to distribute new builds to Firebase. There is a space for improvement to have `release notes` on each build to clarify what is being covered with the new update for the PM and testers instead of showing the default release notes.

**Solution:** available solutions from TPC
- after merging a PR to `develop`: 
  ```
  echo "RELEASE_NOTE_CONTENT="$((git log -1 --merges | grep "\[") | grep . && echo "" || echo $(git log -1 --merges --format=%B))""
  ```

- after merging a release PR to `main`
  ```
  echo "RELEASE_NOTE_CONTENT="$(git log --merges --pretty=%B $(git describe --abbrev=0 --tags)..HEAD | grep "\[")""
  ```

![image](https://github.com/nimblehq/android-templates/assets/16315358/13d52d40-f9ff-4813-9817-d70db0cbb068)

<img src="https://github.com/nimblehq/android-templates/assets/16315358/99c9650f-687d-4476-ab23-3d085b58a60d" width=320 />

## Who Benefits?

PM and Testers

**Comment by luongvo** [comment]
@doannimble we can compared with this plugin https://github.com/marketplace/actions/generate-changelog

**Comment by manh-t** [comment]
@luongvo @doannimble I just noticed that the merged commit messages differ between GitHub and Bitbucket.
While the commit message in Bitbucket contains the PR title when merging, Github doesn't.
**Bitbucket**:
![image](https://github.com/nimblehq/flutter-templates/assets/60863885/66170713-73d4-4bb8-8f6f-cf0f46b18b77)

**Github**:
![image](https://github.com/nimblehq/flutter-templates/assets/60863885/a50cd39e-a0e5-4ad7-8517-42de2bf46c3b)

=> **That command only works for Bitbucket.**

In Github, we cannot get the title of the PR by using the above command, but instead what we get is the last commit message of the PR, like #270 PoW.

In my opinion, if we are unable to obtain the PR title, we should not display the last commit message of the PR. As an alternative solution, we could include the branch name in the release note. For instance, we could present `Merge pull request #253 from nimblehq/feature/234-secure-storage` in the release note.

The command can become:
```
# Staging
echo "RELEASE_NOTE_CONTENT="$((git log -1 --merges | grep "pull") | grep . && echo "" || echo $(git log -1 --merges --format=%B))""

#Production
echo "RELEASE_NOTE_CONTENT="$(git log --merges --pretty=%B $(git describe --abbrev=0 --tags)..HEAD | grep "pull")""
```

Typically, our branch name consists of the ticket ID and ticket title. The PM can rely on this information to determine what will be included in the build. What do you think?
