### ISSUE TITLE
Add new workflow to automate the mason bundle updating process after modifying the bundle config

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#222]
## Why

@manh-t introduced the new approach to generating the template optional feature by using the [Nested template](https://github.com/felangel/mason/tree/master/packages/mason_cli#nested-templates-partials), with [hooks](https://github.com/felangel/mason/tree/master/packages/mason_cli#hooks-usage) and [bundling](https://github.com/felangel/mason/tree/master/packages/mason_cli#bundling) 🎉 

As [mentioned in this PR description](https://github.com/nimblehq/flutter-templates/pull/201), I made a version update for the `permission_handler` package, and that REQUIRES us to refresh/re-generate the bundle file here by using this command

```
mason bundle bricks/permission_handler -t dart -o bricks/template/hooks/bundles
```

This command is required, same as [`code generator` ](https://github.com/nimblehq/flutter-templates/tree/develop/bricks/template/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D#setup), so forgetting to run it will produce unexpected issues that Mason will use the old partials. Hence, automating this is necessary & essential to reduce manual work in template contribution.

The idea is to create a new workflow (e.g., `generate_mason_bundle`) in the root template, which will execute after the `test` workflow succeeds in executing the above script for necessary bundles, commit and push a new commit for bundle updates in each PR (basically same as [`generate_sample`](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/generate_sample.yml) workflow).
 
## Who Benefits?

Developers who contribute to this template.

**Comment by nmint8m** [comment]
According to [this document](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs), I think we just need to define a new **job** inside the `test.yml` workflow:

> A workflow run is made up of one or more jobs, which run in parallel by default. To run jobs sequentially, you can define dependencies on other jobs using the `jobs.<job_id>.needs` keyword.

So technically, I think the approach for this task in the `test.yml` file is that:

```yml
...
jobs:
  test:
  ...
  generate_mason_bundle:
    # The job generate_mason_bundle identify that the job test must complete successfully
    # before this generate_mason_bundle job will run
    needs: test
	...
```

@luongvo What do you think about this approach?

**Comment by nmint8m** [comment]
If we create a brand new workflow, we will need to use [the `workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) which still resolves our issue, but it will be overused for this case.

Let's just use `jobs.<job_id>.needs`.
