### ISSUE TITLE
As a developer, I can have a CD process to build and deploy the Android app to Firebase App Distribution

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#47]
## Why

As a developer, we need to prepare a CD process to build and deploy the Android app to Firebase (most selected).

Update CD script to build and deploy on each branch:

- `develop`: deploy Staging build to Firebase

- `main`: deploy Production build to Firebase

In the end, we need to build a GitHub Action workflow which is inspired by a workflow on Bitrise from Varun project https://github.com/nimblehq/varun-flutter/blob/c2229cba27d757487299a9254327dd8f506d7003/bitrise.yml#L82-L93
 
## Who Benefits?

Developers

**Comment by sleepylee** [comment]
@luongvo is this to deploy the template_releases or the example/ or the flaggable feature? 🤔

**Comment by luongvo** [comment]
I expect to build and deploy the template app into Firebase. Not sure what's it being called? 🤔

**Comment by sleepylee** [comment]
@luongvo our template itself is a project that started with the `python` script, so it means the `template app` like you mentioned. As you can see, we don't have to deploy to firebase anything from this template app.

The other part is the `templated app` (-ed) - that is a flutter project which will be initialized from this template, and we will definitely need Deployment config for it (to Firebase), and Continuous Deployment (CD) could be another extra configuration via bitrise or github action. As you can see, there will be many things to manage when we break them down into smaller requirements that we can 'plug' into a templated app FROM this template script. 

So, could you please finalize your plan accordingly so we can vote and proceed?

**Comment by manh-t** [comment]
@luongvo @sleepylee from my understanding, deploying to Firebase is a must-have feature (most of our projects use Firebase for the app distribution), so we will implement this task into `.project` dir aka `templated app` as mentioned in #58 .  Please correct me if I'm wrong 🙇  If it is correct, we can proceed with this task in `0.7.0` imo 😄

**Comment by sleepylee** [comment]
that works, @manh-t. btw `.project` sounds like a bad name to me 😄  why wouldn't we use `.template` like rails-template, elixir-template, react-template tho 😛

**Comment by manh-t** [comment]
@sleepylee ah yes, that sounds better 😂  I will update `.project` to `.template` in the related tasks, many thanks 💅

**Comment by luongvo** [comment]
@manh-t that's correct. Also, we need to add a new Action workflow in the root template to generate, execute and test our CD workflow in `.template` project

**Comment by luongvo** [comment]
> that works, @manh-t. btw `.project` sounds like a bad name to me 😄 why wouldn't we use `.template` like rails-template, elixir-template, react-template tho 😛

So how can we mention the template project and the project to be generated in `.template` folder? Would they confuse together?
