### ISSUE TITLE
As a developer, I can have a CD process to build and deploy the iOS app to Firebase App Distribution

### ISSUE THREAD

**Issue by luongvo** [nimblehq/flutter-templates#48]
## Why

As a developer, we need to prepare a CD process to build and deploy the iOS app to Firebase (most selected).

Setup `fastlane match` to setup and sync necessary certificates and provisioning profiles.

Update CD script to build and deploy on each branch:

- `develop`: deploy Staging build to Firebase

- `main`: deploy Production build to Firebase

In the end, we need to build a GitHub Action workflow which is inspired by a workflow on Bitrise from Varun project https://github.com/nimblehq/varun-flutter/blob/c2229cba27d757487299a9254327dd8f506d7003/bitrise.yml#L94-L114
 
## Who Benefits?

Developers

**Comment by markgravity** [comment]
@luongvo Do we really need a workflow to deploy the production build to the Firebase? Cause, we need to configure an ad-hoc provisioning profile here

![CleanShot 2023-03-13 at 15 55 50](https://user-images.githubusercontent.com/17875522/224653115-9a1a08a7-6f3d-4be8-9903-288280566f98.png)

And if we want to create a workflow to deploy to AppStore we need to re-update the above configure to an AppStore provisioning profile.

And to keep for both workflows to work at the same time, we need to find a way to switch this config, usually, we only deploy to production build to Testflight/Appstore only 🤔

**Comment by luongvo** [comment]
@markgravity Can we deploy the iOS `Staging build to Firebase` and the `Production build to Testflight/Appstore`?

**Comment by markgravity** [comment]
> @markgravity Can we deploy the iOS `Staging build to Firebase` and the `Production build to Testflight/Appstore`?

Yes, that is what we are doing on the client project atm 👍
