### ISSUE TITLE
As a developer, I can have a CD process to build and deploy the Android app to Play Store

### ISSUE THREAD

**Issue by manh-t** [nimblehq/flutter-templates#61]
## Why

As a developer, we need to prepare a CD process to build and deploy the Android app to Play Store via `fastlane`

Add CD script to build and deploy on the branch:
- `main`: deploy the Production build to Play Store.

In the end, we need to build a GitHub Action workflow which is inspired by a workflow on Bitrise from Varun project https://github.com/nimblehq/varun-flutter/blob/c2229cba27d757487299a9254327dd8f506d7003/bitrise.yml#L198-L212

## Who Benefits?

Developers

**Comment by sleepylee** [comment]
@manh-t you are using an [RFC] Issue template, please consider updating it with a proper stories template (Chore/Feature)
